//
// Created by Hoque, Mohammad on 15/01/2019.
//

#ifndef QOSMOS_QOSMOS_H
#define QOSMOS_QOSMOS_H

#endif //QOSMOS_QOSMOS_H
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_aznc_android_nativetoyvpn_NativeToyVpnService
 * Method:    getTunnelSock
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_aznc_android_nativetoyvpn_NativeToyVpnService_getTunnelSock
        (JNIEnv *, jobject);

/*
 * Class:     cc_aznc_android_nativetoyvpn_NativeToyVpnService
 * Method:    startTunnel
 * Signature: (Ljava/lang/String;I[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cc_aznc_android_nativetoyvpn_NativeToyVpnService_startTunnel
        (JNIEnv *, jobject, jstring, jint, jbyteArray);

/*
 * Class:     cc_aznc_android_nativetoyvpn_NativeToyVpnService
 * Method:    tunnelLoop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cc_aznc_android_nativetoyvpn_NativeToyVpnService_tunnelLoop
        (JNIEnv *, jobject, jint);

/*
 * Class:     cc_aznc_android_nativetoyvpn_NativeToyVpnService
 * Method:    tunnelStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cc_aznc_android_nativetoyvpn_NativeToyVpnService_tunnelStop
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
